language: crystal

cache:
  directories:
    - amber
    - dist

env:
  - FILENAME=basic_crecto
  - FILENAME=basic_granite
  - FILENAME=default
  - FILENAME=misc_modular
  - FILENAME=react_preact_redux

script:
  - crystal spec "spec/${FILENAME}_spec.cr"

after_success:
  - bash "scripts/build_zips.sh"

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8b26d3879e3a6ff4a75c
    on_success: change
    on_failure: always
    on_start: never

before_deploy:
  - git tag -f dist
  - git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh dist
  - git remote remove gh

deploy:
  provider: releases
  api_key: $API_KEY
  file: "dist/${FILENAME}.zip"
  skip_cleanup: true
  name: Amber Framework Recipes
  body: Automatic build of $TRAVIS_BRANCH at commit $TRAVIS_COMMIT built on $(date +'%F %T %Z').
  prerelease: false
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    branch: master
    repo: amberframework/recipes
